codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        enabled: yes
        target: 70%
        threshold: 1%
        branches: null

    patch:
      default:
        target: auto
        threshold: 1%
        branches: null

    changes:
      default:
        branches: null

  ignore: null

comment: False
  #layout: "header, diff, changes, sunburst, uncovered, tree"
  #branches: null
  #behavior: default
