codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "80...100"

  status:
    project:
      default:
        enabled: yes
        target: 100%
        threshold: 1%
        branches: null

    patch:
      default:
        target: 100%
        threshold: 1%
        branches: null

  ignore: null

comment: False
