branches:
    only: 
        - master

language: python

python:
    - 2.7
    - 3.6
    #- 3.7  Not available yet.  Try again later.

before_install:
    - sudo apt-get install -y libffi-dev
    - export PYTHONPATH=$HOME/lib/python$TRAVIS_PYTHON_VERSION/site-packages/:$PYTHONPATH
    - mkdir $HOME/lib
    - mkdir $HOME/lib/python$TRAVIS_PYTHON_VERSION
    - mkdir $HOME/lib/python$TRAVIS_PYTHON_VERSION/site-packages

install:
    - pip install -U -r requirements.txt
    # Extra packages only needed for testing:
    - pip install -U -r test_requirements.txt
    - pip install -U matplotlib pytest codecov nbval ipykernel

cache:
    - pip: true

script: 
    - python setup.py install --prefix=$HOME
    - cd tests
    - nosetests -vs --with-coverage --cover-package=treecorr
    - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then py.test --nbval Tutorial.ipynb --sanitize-with sanitize.cfg --current-env; fi

after_success:
    - codecov
