#!/usr/bin/env bash

# Note: This is not the recommended way to run the test suite.
# Most of the time, you should run either pytest or nosetests to run the tests.
# However, some of the tests are very slow to do at a full level of precision that we
# would like to target, so the slow version is disabled when running via nosetests or pytest.
# This script exists to run all of these slow tests at the full precision level.
# It is normally only done once before a release.  Not for every commit or even PR.

python='python'
# In case you want to use something else. Like python3. Or maybe an explicit path.

/bin/rm -rf output/*

time $python test_catalog.py || exit
time $python test_config.py || exit
time $python test_nn.py || exit
time $python test_ng.py || exit
time $python test_nk.py || exit
time $python test_gg.py || exit
time $python test_kk.py || exit
time $python test_kg.py || exit
time $python test_nz.py || exit
time $python test_kz.py || exit
time $python test_zz.py || exit
time $python test_nv.py || exit
time $python test_kv.py || exit
time $python test_vv.py || exit
time $python test_nt.py || exit
time $python test_kt.py || exit
time $python test_tt.py || exit
time $python test_nq.py || exit
time $python test_kq.py || exit
time $python test_qq.py || exit
time $python test_ggg.py || exit
time $python test_kkk.py || exit
time $python test_nnn.py || exit
time $python test_index.py || exit
time $python test_twod.py || exit
time $python test_rperp.py || exit
time $python test_kmeans.py || exit
time $python test_reader.py || exit
time $python test_periodic.py || exit
time $python test_patch.py || exit
time $python test_patch3pt.py || exit
time $python test_mpi.py || exit
time $python test_mpi3pt.py || exit
