name: Build wheels and sdist and upload to PyPI

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:

  build_linux_wheels:
    name: Build wheels on standard linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_BUILD: "*manylinux*"
          CIBW_SKIP: cp36* pp*
          CIBW_BEFORE_ALL_LINUX: yum install -y libffi-devel || true

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl

  build_musl_wheels:
    name: Build wheels on musl linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_BUILD: "*musllinux*"
          CIBW_SKIP: cp36* pp*
          # I think musl always uses apk, but it doesn't seem to need ffi installed, so this works.
          CIBW_BEFORE_ALL_LINUX: yum install -y libffi-devel || true

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl

  build_macosx_wheels:
    name: Build wheels on macosx
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_BUILD: "*macosx*"
          CIBW_SKIP: cp36* pp*
          CIBW_BEFORE_ALL_MACOS: brew install libffi || true

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build sdist and upload to PyPI
    needs: [build_linux_wheels, build_musl_wheels, build_macosx_wheels]
    # Just need to build sdist on a single machine
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U numpy setuptools
          pip install -U -r requirements.txt

      - name: Download wheels
        uses: actions/download-artifact@v3
        with:
          path: ./wheels

      - name: Build sdist
        run: |
          python setup.py sdist
          ls -l dist
          tar tvfz dist/TreeCorr-*.tar.gz

      - name: Copy wheels
        run: |
          echo ls -l wheels
          ls -l wheels
          echo ls -l wheels/artifact
          ls -l wheels/artifact
          cp wheels/artifact/*.whl dist
          echo ls -l dist
          ls -l dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            user: rmjarvis
            password: ${{ secrets.PYPI_PASSWORD }}
            verbose: true
